[package]
name = "gzp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
failure = "0.1.8"
flate2 = {version = "~1", features = ["zlib-ng-compat"], default-features = false }
futures = "0.3.16"
structopt = "0.3.22"
tokio = {version = "1.9.0", features = ["full"]}
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
