[package]
name = "gzp"
authors = ["Seth Stadick <sstadick@gmail.com>"]
version = "0.3.1-alpha.0"
edition = "2018"
license = "Unlicense/MIT"
readme = "README.md"
documentation = "https://docs.rs/gzp"
homepage = "https://github.com/sstadick/gzp"
repository = "https://github.com/sstadick/gzp"
categories = ["compression", "concurrency"]
keywords = ["compression", "parallel", "pigz"]
description = "Parallel Gzip Compression"

[lib]
name = "gzp"
path = "src/lib.rs"
bench = false

[features]
default = []
parsnap_default = ["parsnap"]
pargz_default = ["pargz", "flate2_default"]
pargz = [] # pargz enables features within the crate
parsnap = ["snap"] # parsnap enable features within the crate
flate2_default = ["zlib-ng-compat"]
zlib = ["flate2/zlib", "flate2/any_zlib"]
zlib-ng-compat = ["flate2/zlib-ng-compat", "flate2/any_zlib"]
cloudflare_zlib = ["flate2/cloudflare_zlib", "flate2/any_zlib"]

[dependencies]
bytes = "1.0.1"
flate2 = { version = "~1", default-features = false, optional = true }
#libz_sys = { version = "1.1.3", deafult-features = false, optional = true }
num_cpus = "1.13.0"
thiserror = "1.0.26"
snap = { version = "~1", optional = true }
flume = { version = "0.10.8", features = ["async"] }
rayon = "1.5.1"

[dev-dependencies]
proptest = "1.0.0"
tempfile = "3.2.0"
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
